/** Declaration file generated by dts-gen */

declare module "nbt" {

    export const tagTypeNames: {
        "0": string;
        "1": string;
        "10": string;
        "11": string;
        "12": string;
        "2": string;
        "3": string;
        "4": string;
        "5": string;
        "6": string;
        "7": string;
        "8": string;
        "9": string;
    };

    export const tagTypes: {
        byte: number;
        byteArray: number;
        compound: number;
        double: number;
        end: number;
        float: number;
        int: number;
        intArray: number;
        list: number;
        long: number;
        longArray: number;
        short: number;
        string: number;
    };

    export function Reader(buffer: any): any;

    export function Writer(): any;

    export function parse<T extends object>(data: Buffer | ArrayBuffer, callback: (error: object | null, result: { name: string; value: T }) => any): void;

    export function parseUncompressed<T extends object>(data: Buffer | ArrayBuffer): T;

    export function writeUncompressed(value: any): ArrayBuffer;
}
